language: java

jdk:
  - openjdk8

before_install:
  - chmod +x mod/gradlew

script:
  - cd mod/
  - ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key:
    secure: do+IrNYVOQbjQpxCauizU2k75pXyFRBk9WD/4XcHVh66Lf6UHQPRmhOvSb2XoMQrXRoXZtGiETbuVuoQYV5XmbVb/d2ndA/fxckfxIpXaDEwSB6r2T7PPVknItJpyR02vJgrIRC1PXCrFT4cHbnZubZkNAfWh64QIeuGw2UnZEE=
  file_glob: true
  file: build/libs/*.jar
  on:
    repo: zsawyer/MumbleLink
    branch: QnD-MC_JNA
    tags: true
  skip_cleanup: trues
  draft: true